---
- name: firewall01 playbook
  hosts: all
  tasks:
  - name: required packages
    apt: name={{item}} state=latest
    with_items:
    - git
    - openssh-server
    
  - name: set dns
    copy: 
      dest: /etc/resolv.conf
      content: \
        search
        nameserver 62.210.16.6
        nameserver 62.210.16.7
  #- name: 
  #  copy: 
  #    dest: /etc/network/interfaces.d/eth0
  #    content: 
