---
# manual actions to take on fresh install before debian will work
# create separate 'vswitch' & 'portgroup'
# add secondary nic in 'portgroup'
# get primary interface up, with correct mac address
# add a proper mirror: deb http://ftp.{{country}}.debian.org/debian {{distro}} main contrib non-free
# apt-get update && apt-get install ansible git
# apt-get install software-properties-common open-vm-tools
- name: firewall playbook (written with online.net esx failover ip in mind). Debian assumed.
  hosts: 127.0.0.1 
  connection: local
  vars:
  - extif: ens192
  - extip: 163.172.224.245
  - intif: ens224
  - intip: 10.0.0.1
  - distro: stretch
  - mirror: http://ftp.fr.debian.org
  tasks:
  - name: add repos with copy, because apt_repository is buggy as hell in this version
    copy: 
      dest: /etc/apt/sources.list
      content: "deb http://security.debian.org/ {{distro}}/updates main contrib non-free\ndeb-src http://security.debian.org/ {{distro}}/updates main contrib non-free\ndeb {{mirror}} {{contrib}} main contrib non-free\n deb {{mirror}} jessie-updates main contrib non-free\n deb-src {{mirror}} {{distro}}-updates main contrib non-free\ndeb http://ftp.debian.org/debian {{contrib}}-backports main contrib non-free\n"
      backup: yes
    tags:
    - apt
  - name: run apt-get update
    command: apt-get update
    tags:
    - apt
  - name: required packages
    apt: name={{item}} state=latest
    with_items:
    - git #actually git needs to be installed before ansible-pull can run...
    - openssh-server
    - libpam-google-authenticator
    - sudo
    - python-pip
    - open-vm-tools
    - software-properties-common
    
#  - name: get non-antique version of ansible
#    pip: name=ansible state=present
#    tags:
#    - pip
    
  - name: set dns
    copy: 
      dest: /etc/resolv.conf
      content: "search\nnameserver 62.210.16.6\nnameserver 62.210.16.7\n"
  - name: eth0 - outside facing
    copy: 
      dest: /etc/network/interfaces.d/{{extif}}
      content: "auto {{extif}}\n iface {{extif}} inet static\n address {{extip}}\n netmask 255.255.255.255\n pointopoint 62.210.0.1\n gateway 62.210.0.1\n"
  - name: eth1 - local traffic
    copy: 
      dest: /etc/network/interfaces.d/{{intif}}
      content: "auto {{intif}}\n iface {{intif}} inet static\n address {{intip}}\n netmask 255.0.0.0\n"
  - command: ifup eth0
  - command: ifup eth1
  - name: activate forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
  - iptables: # Allow related and established connections
      chain: INPUT
      ctstate: ESTABLISHED,RELATED
      jump: ACCEPT    
  - name: iptables forward rule #iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    iptables:
      table: nat
      chain: POSTROUTING
      out_interface: eth0
      jump: MASQUERADE
      comment: activate outgoing ip masquerading
  - iptables: # Forward port 80 to 8080
      table: nat
      chain: PREROUTING
      in_interface: eth0
      protocol: tcp
      match: tcp
      destination_port: 80
      jump: REDIRECT
      #to_destination: webr01
      to_ports: 8080
      comment: Redirect web traffic to port 8080
  
    
    
