---
- name: firewall01 playbook
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: add repos with copy, because apt_repository is buggy as hell in this (1.7*) version
    copy: 
      dest: /etc/apt/sources.list
      content: "deb http://ftp.debian.org/debian/ jessie main contrib non-free\ndeb http://security.debian.org/ jessie/updates main contrib non-free\ndeb-src http://security.debian.org/ jessie/updates main contrib non-free\ndeb http://ftp.debian.org/debian/ jessie-updates main contrib non-free\ndeb-src http://ftp.debian.org/debian/ jessie-updates main contrib non-free\n"
  - command: apt-get update
  - name: required packages
    apt: name={{item}} state=latest
    with_items:
    - git #actually git needs to be installed before ansible-pull can run...
    - openssh-server
    
  - name: set dns
    copy: 
      dest: /etc/resolv.conf
      content: "search\nnameserver 62.210.16.6\nnameserver 62.210.16.7\n"
  - name: eth0 - outside facing
    copy: 
      dest: /etc/network/interfaces.d/eth0
      content: "auto eth0\n iface eth0 inet static\n address 163.172.201.212\n netmask 255.255.255.255\n pointopoint 62.210.0.1\n gateway 62.210.0.1\n"
  - name: eth1 - local raffic
    copy: 
      dest: /etc/network/interfaces.d/eth1
      content: "auto eth0\n iface eth1 inet static\n address 10.0.0.1\n netmask 255.0.0.0\n"
