---
- name: mailserver setup (debian)
  hosts: all
  tasks:
  - name: common packages
    apt: name={{item}} state=present
    with_items:
    - vim
    - tmux
    - nmon
    - screen
     
  - name: mail server packages
    apt: name={{item}} state=present
    with_items:
    #- dovecot-imapd
    #- dovecot-gssapi
    - postfix
    - roundcube #no longer in debian?
    - offlineimap
    - maildir-filter
    - maildir-utils
    - maildir-utils-extra
    - maildirsync
    - mutt
    - isync
    - nmzmail
    
  - name: users
    user: name={{item}}
    with_items:
    - ovhdave
    - ovhpostmaster
    - ovhucx
    
    
    
  - name: cron ansible-pull
    cron: job="ansible-pull -U https://github.com/ucxdvd/ansible-pull -i localhost,127.0.0.1," minute=* name="launch ansible-pull"
  
