---
- name: typical packages for all sbc's
  hosts: all
  vars:
  - pippackages:
    - pushbullet.py
  - packages:
    - common:
      - git
    - configmgmt:
      - ansible
    - zeroconf:
      - avahi-discover
      - avahi-daemon
      - libnss-mdns
    - nfs
      - nfs-kernel-server
      - rpcbind
      - nfs-common
    - security
      - libpam-google-authenticator
    - messaging
      - python-pip
      - libnet-http-perl
      - perl-libwww-perl 
      - perl-LWP-Protocol-https
      - python-xmpp
  tasks:
    - name: install all os packages
      apt: name={{item}} state=present
      with_items: 
      - packages.common
      - packages.configmgmt
      - packages.zeroconf
      - packages.nfs
      - packages.security
      - packages.messaging
    - name: install all pip packages
      pip: name={{item}} state=present
      with_items:
      - {{pippackages}}
