---
- name: typical packages for all sbc's
  hosts: all
  vars:
  tasks:
  - name: install os packages
    apt: name={{item}} state=present
    with_items:
    - git
    - ansible
    - avahi-discover
    - avahi-daemon
    - libnss-mdns
    - nfs-kernel-server
    - rpcbind
    - nfs-common
    - libpam-google-authenticator
    - python-pip
#    - libnet-http-perl
    - libwww-perl 
    - liblwp-protocol-https-perl
    - python-xmpp
    
  - name: install all pip packages
    pip: name={{item}} state=present
    with_items:
    - pushbullet.py
